locals {
  regions = {
		"australiacentral"   = "auc",
    "australiacentral2"  = "auc2",
    "australiaeast"      = "aue",
    "australiasoutheast" = "ause",
    "brazilsouth"        = "brs",
    "brazilsoutheast"    = "brse",
    "canadacentral"      = "cac",
    "canadaeast"         = "cae",
    "centralindia"       = "cin",
    "centralus"          = "cus",
    "eastasia"           = "eaz",
    "eastus"             = "eus",
    "eastus2"            = "eus2",
    "francecentral"      = "frc",
    "francesouth"        = "frs",
    "germanynorth"       = "den",
    "germanywestcentral" = "dewc",
		"israelcentral"      = "isc",
		"italynorth"         = "itn",
    "japaneast"          = "jpe",
    "japanwest"          = "jpw",
    "jioindiacentral"    = "inc",
		"jioindiawest"       = "inw",
		"koreacentral"       = "krc",
    "koreasouth"         = "krs",
    "northcentralus"     = "ncus",
    "northeurope"        = "neu",
    "norwayeast"         = "noe",
    "norwaywest"         = "now",
    "polandcentral"      = "poc",
		"qatarcentral"       = "qac",
		"southafricanorth"   = "zan",
    "southafricawest"    = "zaw",
    "southcentralus"     = "scus",
    "southeastasia"      = "seaz",
    "southindia"         = "sin",
		"swedencentral"      = "swc",
    "switzerlandnorth"   = "sun",
    "switzerlandwest"    = "suw",
    "uaecentral"         = "aec",
    "uaenorth"           = "aen",
    "uksouth"            = "uks",
    "ukwest"             = "ukw",
    "westcentralus"      = "wcus",
    "westeurope"         = "weu",
    "westindia"          = "win",
    "westus"             = "wus",
    "westus2"            = "wus2",
    "westus3"            = "wus3",
  }

  region_short_name = var.region == null ? "" : local.regions[var.region]

  region_short_name_map = local.regions
}
